two new features
'd', 'u'
still not able to play sound using pyttsx3 in .exe
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
[7644] Failed to execute script voice_recorder